# Serverless Framework Configuration for Trading Bot
# This configuration deploys your trading bot to AWS Lambda

service: nifty-banknifty-trading-bot

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: ap-south-1  # Mumbai region for lower latency
  stage: ${opt:stage, 'dev'}
  memorySize: 512
  timeout: 300  # 5 minutes timeout
  
  # IAM permissions
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: '*'
        - Effect: Allow
          Action:
            - ssm:GetParameter
            - ssm:GetParameters
          Resource: '*'

  # Environment variables
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    
    # Trading API credentials
    KITE_API_KEY: ${env:KITE_API_KEY}
    KITE_API_SECRET: ${env:KITE_API_SECRET}
    KITE_ACCESS_TOKEN: ${env:KITE_ACCESS_TOKEN}
    
    # Telegram bot credentials
    TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}
    TELEGRAM_USER_ID: ${env:TELEGRAM_USER_ID}
    
    # Database credentials
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_KEY: ${env:SUPABASE_KEY}
    
    # Trading configuration
    TRADING_CAPITAL: ${env:TRADING_CAPITAL, '100000'}
    ENABLE_PAPER_TRADING: ${env:ENABLE_PAPER_TRADING, 'true'}
    MAX_DAILY_LOSS_PERCENT: ${env:MAX_DAILY_LOSS_PERCENT, '3'}

# Lambda functions
functions:
  # Main trading function - executes during market hours with sophisticated engine
  mainTrading:
    handler: lambda_functions/main_trading/sophisticated_handler.lambda_handler
    description: Sophisticated trading engine with market intelligence and database integration
    timeout: 900  # 15 minutes for complex analysis
    memorySize: 1769  # Increased memory for sophisticated operations + large packages
    events:
      - schedule:
          rate: rate(5 minutes)  # Every 5 minutes during market hours
          enabled: true
          input:
            action: trading
      # HTTP endpoint for manual triggering
      - http:
          path: trading/execute
          method: post
          private: false

  # Pre-market analysis function
  preMarketAnalysis:
    handler: lambda_functions/main_trading/sophisticated_handler.lambda_handler
    description: Pre-market analysis and preparation with market intelligence
    timeout: 600  # 10 minutes for analysis
    memorySize: 1769  # Increased memory for sophisticated packages
    events:
      - schedule:
          rate: cron(30 3 ? * MON-FRI *)  # 9:00 AM IST (3:30 UTC)
          enabled: true
          input:
            action: analysis

  # Post-market reporting function  
  postMarketReporting:
    handler: lambda_functions/main_trading/sophisticated_handler.lambda_handler
    description: Post-market analysis and daily reporting with performance metrics
    timeout: 600  # 10 minutes for reporting
    memorySize: 1769  # Increased memory for sophisticated packages
    events:
      - schedule:
          rate: cron(0 11 ? * MON-FRI *)  # 4:30 PM IST (11:00 UTC)
          enabled: true
          input:
            action: analysis

  # Health check function
  healthCheck:
    handler: lambda_functions/main_trading/sophisticated_handler.lambda_handler
    description: System health check and monitoring with database connectivity
    events:
      - schedule:
          rate: cron(0 4 ? * MON-FRI *)  # 9:30 AM IST (4:00 UTC)
          enabled: true
          input:
            action: health_check

# CloudFormation resources
resources:
  Resources:
    # CloudWatch Log Groups will be created automatically by Lambda

    # CloudWatch Alarms for monitoring
    TradingErrorAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: ${self:service}-${self:provider.stage}-trading-errors
        AlarmDescription: Alert when trading function has errors
        MetricName: Errors
        Namespace: AWS/Lambda
        Statistic: Sum
        Period: 300
        EvaluationPeriods: 1
        Threshold: 1
        ComparisonOperator: GreaterThanOrEqualToThreshold
        Dimensions:
          - Name: FunctionName
            Value: ${self:service}-${self:provider.stage}-mainTrading

    # Dead Letter Queue for failed executions
    TradingDLQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-dlq
        MessageRetentionPeriod: 1209600  # 14 days

# Plugins
plugins:
  - serverless-python-requirements

# Custom configuration
custom:
  # Python requirements configuration - Optimized sophisticated system
  pythonRequirements:
    dockerizePip: true
    fileName: lambda_functions/sophisticated_requirements.txt
    # Use INLINE packaging instead of layer to avoid 250MB layer limit
    layer: false
    # Aggressive optimization for sophisticated packages
    slim: true
    strip: true
    zip: true
    # Remove unnecessary files to reduce size
    pipCmdExtraArgs:
      - --no-cache-dir
      - --compile
    noDeps:
      # Exclude packages available in Lambda runtime
      - boto3
      - botocore
      - urllib3
      - requests
    # Additional size optimizations
    pythonBin: python3.9
    useStaticCache: true
    useDownloadCache: true

  # Alerts configuration (disabled for simpler deployment)
  # alerts:
  #   stages:
  #     - dev
  #     - prod
  #   topics:
  #     alarm:
  #       topic: ${self:service}-${self:provider.stage}-alerts
  #       notifications:
  #         - protocol: email
  #           endpoint: ${env:ALERT_EMAIL, 'your-email@example.com'}
  #   alarms:
  #     - functionErrors
  #     - functionThrottles
  #     - functionInvocations

# Package configuration
package:
  patterns:
    - '!node_modules/**'
    - '!.git/**'
    - '!.vscode/**'
    - '!tests/**'
    - '!docs/**'
    - '!*.md'
    - '!.env*'
    - '!venv/**'
    - '!__pycache__/**'
    - '!.pytest_cache/**'
    - 'src/**'
    - 'lambda_functions/**'