# GitHub Actions Workflow for AWS Lambda Deployment
# Automatically deploys trading bot to AWS Lambda on push to main branch

name: Deploy Trading Bot to AWS Lambda

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'lambda_functions/**'
      - 'serverless.yml'
      - 'lambda_functions/lambda_requirements.txt'
  workflow_dispatch: # Allow manual triggering
    inputs:
      stage:
        description: 'Deployment stage (dev/prod)'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - prod

env:
  AWS_REGION: ap-south-1
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.9'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('lambda_functions/lambda_requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r lambda_functions/lambda_requirements.txt
        pip install pytest pytest-cov
        
    - name: Run tests
      run: |
        # Run unit tests (add when available)
        echo "Tests would run here"
        # pytest tests/ -v --cov=src --cov-report=xml
        
    - name: Validate configuration
      run: |
        python -c "
        import sys, os
        sys.path.append('src')
        print('✅ Python imports working')
        
        # Validate serverless.yml
        import yaml
        with open('serverless.yml') as f:
            config = yaml.safe_load(f)
        print('✅ Serverless config valid')
        
        print('✅ All validations passed')
        "

  deploy:
    name: Deploy to AWS Lambda
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    
    strategy:
      matrix:
        stage: [dev] # Add 'prod' when ready for production
        
    environment: 
      name: ${{ matrix.stage }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Install Serverless Framework
      run: |
        npm install -g serverless@3
        serverless --version
        
    - name: Install Serverless plugins
      run: |
        npm install serverless-python-requirements
        npm install serverless-plugin-aws-alerts
        
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('lambda_functions/lambda_requirements.txt') }}
        
    - name: Set up environment variables
      run: |
        # Store secrets in AWS Parameter Store
        echo "Setting up AWS Parameter Store values..."
        
        # Only set if parameters don't exist (to avoid overwriting)
        aws ssm put-parameter \
          --name "/trading-bot/kite/api-key" \
          --value "${{ secrets.KITE_API_KEY }}" \
          --type "SecureString" \
          --overwrite || true
          
        aws ssm put-parameter \
          --name "/trading-bot/kite/api-secret" \
          --value "${{ secrets.KITE_API_SECRET }}" \
          --type "SecureString" \
          --overwrite || true
          
        aws ssm put-parameter \
          --name "/trading-bot/kite/access-token" \
          --value "${{ secrets.KITE_ACCESS_TOKEN }}" \
          --type "SecureString" \
          --overwrite || true
          
        aws ssm put-parameter \
          --name "/trading-bot/telegram/bot-token" \
          --value "${{ secrets.TELEGRAM_BOT_TOKEN }}" \
          --type "SecureString" \
          --overwrite || true
          
        aws ssm put-parameter \
          --name "/trading-bot/telegram/user-id" \
          --value "${{ secrets.TELEGRAM_USER_ID }}" \
          --type "String" \
          --overwrite || true
          
        aws ssm put-parameter \
          --name "/trading-bot/supabase/url" \
          --value "${{ secrets.SUPABASE_URL }}" \
          --type "String" \
          --overwrite || true
          
        aws ssm put-parameter \
          --name "/trading-bot/supabase/key" \
          --value "${{ secrets.SUPABASE_KEY }}" \
          --type "SecureString" \
          --overwrite || true
          
        echo "✅ AWS Parameter Store setup complete"
        
    - name: Deploy to AWS Lambda
      run: |
        echo "🚀 Deploying to AWS Lambda (${{ matrix.stage }} stage)..."
        
        # Deploy using Serverless Framework
        serverless deploy \
          --stage ${{ matrix.stage }} \
          --region ${{ env.AWS_REGION }} \
          --verbose
          
        echo "✅ Deployment completed successfully!"
        
    - name: Test deployment
      run: |
        echo "🧪 Testing deployment..."
        
        # Test main trading function
        aws lambda invoke \
          --function-name "nifty-banknifty-trading-bot-${{ matrix.stage }}-mainTrading" \
          --payload '{"action": "test", "force_run": true}' \
          --cli-binary-format raw-in-base64-out \
          response.json
          
        echo "📋 Lambda response:"
        cat response.json | jq '.'
        
        # Check if response indicates success
        if jq -e '.statusCode == 200' response.json > /dev/null; then
          echo "✅ Lambda function test successful"
        else
          echo "❌ Lambda function test failed"
          exit 1
        fi
        
    - name: Send deployment notification
      if: success()
      run: |
        echo "📢 Sending deployment notification..."
        
        # Send notification via Lambda function
        aws lambda invoke \
          --function-name "nifty-banknifty-trading-bot-${{ matrix.stage }}-mainTrading" \
          --payload '{"action": "deployment_notification", "stage": "${{ matrix.stage }}"}' \
          --cli-binary-format raw-in-base64-out \
          notification_response.json
          
        echo "✅ Deployment notification sent"
        
    - name: Update deployment status
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ Deployment Status: SUCCESS"
          echo "🎉 Trading bot is now running on AWS Lambda!"
          echo "📊 Stage: ${{ matrix.stage }}"
          echo "🌍 Region: ${{ env.AWS_REGION }}"
          echo "⏰ Deployed at: $(date -u)"
        else
          echo "❌ Deployment Status: FAILED"
          echo "💡 Check the logs above for error details"
        fi

  # Security scan job
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run security scan
      uses: securecodewarrior/github-action-add-sarif@v1
      with:
        sarif-file: 'security-scan.sarif'
        
    - name: Check for secrets in code
      run: |
        echo "🔍 Scanning for hardcoded secrets..."
        
        # Check for common secret patterns (basic check)
        if grep -r -i "api_key\|api_secret\|password\|token" --include="*.py" src/ lambda_functions/ | grep -v "env\|ENV\|environment"; then
          echo "⚠️ Potential hardcoded secrets found!"
          echo "Make sure all secrets are stored in environment variables"
        else
          echo "✅ No hardcoded secrets detected"
        fi

# Workflow complete notification
  notify-completion:
    name: Notify Completion
    runs-on: ubuntu-latest
    needs: [deploy, security-scan]
    if: always()
    
    steps:
    - name: Send completion notification
      run: |
        if [ "${{ needs.deploy.result }}" == "success" ]; then
          echo "🎉 Deployment pipeline completed successfully!"
          echo "Your Nifty/BankNifty trading bot is now running autonomously in AWS Lambda"
        else
          echo "❌ Deployment pipeline failed"
          echo "Please check the workflow logs for details"
        fi